<a href="https://colab.research.google.com/github/nurfnick/Data_Viz/blob/main/Content/Data_Cleaning/Exam3Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exam 3 Review

Utilizing the bank dataset https://github.com/nurfnick/Data_Viz/blob/main/Data_Sets/bank.csv answer the following questions.

1. What are the datatypes for each column.  Comment on the appropriateness and change any easy/obvious ones.
2. Using regular expresssions, remove the hyphen "-" from any job and replace it with a space.
3. Convert any place where pdays is -1 to NaN.
4. Fill the NaN in pdays with a zero.
5. Compute the mean and median of balance when grouped by job.
6. Add a column that is a datetime.  Use year of 2020.
7. Which day of the week (Monday, Tuesday, ect.) had the most approved loans, y = yes.
8. Create an indicator column that shows if the person has more than \$500 in their acocunt.
9. Are divorced, admin people given loans at a higher rate?
10. Which job is most likely to have a default on their record?
11. Do highly educated people have more or less cellular phones than on average?
12. What is the maritial status of the person with the maximum balance?
12. Write another question based on your knowledge of the dataset.

In [45]:
import pandas as pa

df = pa.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/Data_Sets/bank.csv')

df.head(20)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
5,35,management,single,tertiary,no,747,no,no,cellular,23,feb,141,2,176,3,failure,no
6,36,self-employed,married,tertiary,no,307,yes,no,cellular,14,may,341,1,330,2,other,no
7,39,technician,married,secondary,no,147,yes,no,cellular,6,may,151,2,-1,0,unknown,no
8,41,entrepreneur,married,tertiary,no,221,yes,no,unknown,14,may,57,2,-1,0,unknown,no
9,43,services,married,primary,no,-88,yes,yes,cellular,17,apr,313,1,147,2,failure,no
10,39,services,married,secondary,no,9374,yes,no,unknown,20,may,273,1,-1,0,unknown,no
11,43,admin.,married,secondary,no,264,yes,no,cellular,17,apr,113,2,-1,0,unknown,no
12,36,technician,married,tertiary,no,1109,no,no,cellular,13,aug,328,2,-1,0,unknown,no
13,20,student,single,secondary,no,502,no,no,cellular,30,apr,261,1,-1,0,unknown,yes
14,31,blue-collar,married,secondary,no,360,yes,yes,cellular,29,jan,89,1,241,1,failure,no
15,40,management,married,tertiary,no,194,no,yes,cellular,29,aug,189,2,-1,0,unknown,no
16,56,technician,married,secondary,no,4073,no,no,cellular,27,aug,239,5,-1,0,unknown,no
17,37,admin.,single,tertiary,no,2317,yes,no,cellular,20,apr,114,1,152,2,failure,no
18,25,blue-collar,single,primary,no,-221,yes,no,unknown,23,may,250,1,-1,0,unknown,no
19,31,services,married,secondary,no,132,no,no,cellular,7,jul,148,1,152,1,other,no

In [46]:
df.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

Marital status can I make true/false...

In [47]:
df.marital.unique()

array(['married', 'single', 'divorced'], dtype=object)

I should not make this a booleen.  The last column could be booleen but lets check...

In [48]:
df.y.unique()

array(['no', 'yes'], dtype=object)

In [49]:
df['y'] = (df['y'] == 'yes')

In [50]:
df.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y              bool
dtype: object

##2
Using regular expresssions, remove the hyphen "-" from any job and replace it with a space.

In [51]:
df['job'] = df['job'].replace('-', ' ')

In [52]:
df.job

0          unemployed
1            services
2          management
3          management
4         blue-collar
            ...
4516         services
4517    self-employed
4518       technician
4519      blue-collar
4520     entrepreneur
Name: job, Length: 4521, dtype: object

## 3

Convert any place where pdays is -1 to NaN.

In [53]:
import numpy as np

df['pdays'] = df['pdays'].replace(-1, np.nan)

df.pdays

0         NaN
1       339.0
2       330.0
3         NaN
4         NaN
        ...
4516      NaN
4517      NaN
4518      NaN
4519    211.0
4520    249.0
Name: pdays, Length: 4521, dtype: float64

In [54]:
df['pdays'].isna()

0        True
1       False
2       False
3        True
4        True
        ...
4516     True
4517     True
4518     True
4519    False
4520    False
Name: pdays, Length: 4521, dtype: bool

# 4

Fill the NaN in pdays with a zero.

In [55]:
df['pdays'] = df['pdays'].fillna(0)

## 5

Compute the mean and median of balance when grouped by job.

In [56]:
df.groupby('job')['balance'].agg(['mean','median'])

                      mean  median
job
admin.         1226.736402   430.0
blue-collar    1085.161734   408.5
entrepreneur   1645.125000   365.5
housemaid      2083.803571   296.5
management     1766.928793   577.0
retired        2319.191304   672.5
self-employed  1392.409836   483.0
services       1103.956835   288.0
student        1543.821429   422.5
technician     1330.996094   434.5
unemployed     1089.421875   473.5
unknown        1501.710526   655.5

## 6
Add a column that is a datetime. Use year of 2020.

In [75]:
df['datetime_column'] = pa.to_datetime(df['month'] + ' ' + df['day'].astype(str) + ' 2020', format='%b %d %Y')

## 7
Which day of the week (Monday, Tuesday, ect.) had the most approved loans, y = yes.

In [82]:
df['day_of_week'] = df['datetime_column'].dt.dayofweek

In [83]:
df.groupby('day_of_week')['y'].sum()

day_of_week
0     70
1    107
2     93
3    105
4     81
5     36
6     29
Name: y, dtype: int64

# 11
Do highly educated people have more or less cellular phones than on average?

In [84]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,datetime_column,day_of_week
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,0.0,0,unknown,False,2020-10-19,0
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339.0,4,failure,False,2020-05-11,0
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330.0,1,failure,False,2020-04-16,3
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,0.0,0,unknown,False,2020-06-03,2
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,0.0,0,unknown,False,2020-05-05,1

In [85]:
df.education.unique()

array(['primary', 'secondary', 'tertiary', 'unknown'], dtype=object)

primary -> Low Ed

secondary -> moderate

tertiary -> highly educated

unknown -> who knows...

In [90]:

((df['contact'] == 'cellular') & (df['education'] == 'tertiary')).sum()/((df['contact'] == 'cellular') & (df['education'] == 'tertiary')).count()

np.float64(0.22384428223844283)

In [94]:
((df['contact'] == 'cellular') & ((df['education'] == 'primary') | (df['education'] == 'secondary'))).sum()/((df['contact'] == 'cellular') & ((df['education'] == 'primary') | (df['education'] == 'secondary'))).count()

np.float64(0.3957089139570891)