<a href="https://colab.research.google.com/github/nurfnick/Data_Viz/blob/main/Content/Data_Cleaning/OneHotDiscussion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub
path = kagglehub.dataset_download("jessicali9530/animal-crossing-new-horizons-nookplaza-dataset")

Using Colab cache for faster access to the 'animal-crossing-new-horizons-nookplaza-dataset' dataset.

In [6]:
import pandas as pd
df = pd.read_csv(path + "/achievements.csv")

df.head()

,Name,Award Criteria,#,Internal ID,Internal Name,Internal Category,Num of Tiers,Tier 1,Tier 2,Tier 3,...,Tier 5,Reward Tier 1,Reward Tier 2,Reward Tier 3,Reward Tier 4,Reward Tier 5,Reward Tier 6,Sequential,Version,Unique Entry ID
0,(island name) Miles!,Awarded when Nook Miles program is first unlocked,1,53,ImmigratetoIsland,Event,1,1,0,0,...,0,500,500,1000,2000,3000,0,Yes,1.0.0,QvQq6d4qJgCiBkMLX
1,Angling for Perfection!,Number of total fish caught,2,0,CatchFish,Fish,5,10,100,500,...,5000,300,500,1000,2000,3000,0,Yes,1.0.0,wkj9WzycBpxtq6CDG
2,Island Ichthyologist,Number of unique fish caught,3,3,FillFishList,Fish,5,10,20,40,...,80,300,500,1000,2000,3000,0,Yes,1.0.0,Ajpkv8wXcZLqM8bMT
3,Island Togetherness,Number of days in which you've talked to every...,4,68,GreetAllVillager,Communication,5,1,10,20,...,50,300,500,1000,2000,3000,0,Yes,1.0.0,syoxyxWL7ymwpKpGN
4,You've Got the Bug,Number of total bugs caught,5,1,CatchInsect,Insect,5,10,100,500,...,5000,300,500,1000,2000,3000,0,Yes,1.0.0,weJ4f9MDdBuzLBrBM

In [11]:
df["Internal Category"] = df["Internal Category"].astype("category")

In [12]:
df.head()

,Name,Award Criteria,#,Internal ID,Internal Name,Internal Category,Num of Tiers,Tier 1,Tier 2,Tier 3,...,Tier 5,Reward Tier 1,Reward Tier 2,Reward Tier 3,Reward Tier 4,Reward Tier 5,Reward Tier 6,Sequential,Version,Unique Entry ID
0,(island name) Miles!,Awarded when Nook Miles program is first unlocked,1,53,ImmigratetoIsland,Event,1,1,0,0,...,0,500,500,1000,2000,3000,0,Yes,1.0.0,QvQq6d4qJgCiBkMLX
1,Angling for Perfection!,Number of total fish caught,2,0,CatchFish,Fish,5,10,100,500,...,5000,300,500,1000,2000,3000,0,Yes,1.0.0,wkj9WzycBpxtq6CDG
2,Island Ichthyologist,Number of unique fish caught,3,3,FillFishList,Fish,5,10,20,40,...,80,300,500,1000,2000,3000,0,Yes,1.0.0,Ajpkv8wXcZLqM8bMT
3,Island Togetherness,Number of days in which you've talked to every...,4,68,GreetAllVillager,Communication,5,1,10,20,...,50,300,500,1000,2000,3000,0,Yes,1.0.0,syoxyxWL7ymwpKpGN
4,You've Got the Bug,Number of total bugs caught,5,1,CatchInsect,Insect,5,10,100,500,...,5000,300,500,1000,2000,3000,0,Yes,1.0.0,weJ4f9MDdBuzLBrBM

In [15]:
df["Internal Category"].cat.categories

Index(['Communication', 'DIY', 'Event', 'Fish', 'HHA', 'Insect', 'LandMaking',
       'Money', 'MyDesign', 'Negative', 'Plant', 'Smartphone'],
      dtype='object')

In [19]:
pd.get_dummies(df["Internal Category"]).astype(int).shape

(84, 12)

In [21]:
pd.get_dummies(df['Name'])

,(island name) Icons,(island name) Miles!,Active Island Resident,Angling for Perfection!,Bell Ringer,Birthday Celebration,Bona Fide Bone Finder!,Bug-Off!,Bugs Don't Bug Me,Bulletin-Board Benefit,...,Taking the Sting Out,That's One Smart Phone,Tomorrow's Trees Today,Trash Fishin',Trashed Tools,True Friends,True Patron of the Arts,Wishes Come True,Wispy Island Secrets,You've Got the Bug
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
80,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
81,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
82,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
83,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
model = OneHotEncoder()

newdf = model.fit_transform(df)

In [28]:
newdf.shape

(84, 618)

In [31]:
print(newdf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1764 stored elements and shape (84, 618)>
  Coords	Values
  (0, 1)	1.0
  (0, 117)	1.0
  (0, 168)	1.0
  (0, 299)	1.0
  (0, 386)	1.0
  (0, 422)	1.0
  (0, 432)	1.0
  (0, 439)	1.0
  (0, 448)	1.0
  (0, 461)	1.0
  (0, 476)	1.0
  (0, 491)	1.0
  (0, 508)	1.0
  (0, 513)	1.0
  (0, 517)	1.0
  (0, 521)	1.0
  (0, 525)	1.0
  (0, 527)	1.0
  (0, 531)	1.0
  (0, 532)	1.0
  (0, 565)	1.0
  (1, 3)	1.0
  (1, 157)	1.0
  (1, 169)	1.0
  (1, 252)	1.0
  :	:
  (82, 527)	1.0
  (82, 531)	1.0
  (82, 532)	1.0
  (82, 575)	1.0
  (83, 2)	1.0
  (83, 158)	1.0
  (83, 251)	1.0
  (83, 272)	1.0
  (83, 364)	1.0
  (83, 422)	1.0
  (83, 436)	1.0
  (83, 440)	1.0
  (83, 454)	1.0
  (83, 468)	1.0
  (83, 481)	1.0
  (83, 499)	1.0
  (83, 507)	1.0
  (83, 513)	1.0
  (83, 517)	1.0
  (83, 521)	1.0
  (83, 525)	1.0
  (83, 527)	1.0
  (83, 531)	1.0
  (83, 532)	1.0
  (83, 564)	1.0